name: excel_to_json
description: >
  A Flutter package that converts Excel (.xlsx) files to JSON format. 
  Features: multiple worksheets support, type-safe cell conversion, 
  configurable options, comprehensive error handling, and cross-platform compatibility.
version: 1.5.0
homepage: https://github.com/vitoramaral10/excel_to_json
repository: https://github.com/vitoramaral10/excel_to_json
issue_tracker: https://github.com/vitoramaral10/excel_to_json/issues
documentation: https://github.com/vitoramaral10/excel_to_json#readme
funding:
  - https://github.com/sponsors/vitoramaral10

topics:
  - excel
  - json
  - converter
  - spreadsheet
  - xlsx

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  excel: ^4.0.3
  file_picker: ^10.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
